import tkinter
from tkinter import *
'''import Person6n
import Widgets'''

master = Tk()
master.title("Roommate Match")
master.wm_iconbitmap("Troll_Face.ico")

def var_states():
    print("Yes: %d, /nNo: %d" % (var1.get(), var2.get()))

#def callback():
    
    
Label(master, text="First Name").grid(row=0)
Label(master, text="Last Name").grid(row=1)
Label(master, text="Age").grid(row=2)
Label(master, text="What state are you from? (please enter state abbreviation)"
      ).grid(row=3)
Label(master, text="Leave a personal message, or brief description of yourself"
      ).grid(row=4)
Label(master, text="Do you have any dietary restirctions be it from allergies or personal choice?").grid(row=5)
var1 = IntVar()
Checkbutton(master, text="yes", variable = var1).grid(row=5, column=1, sticky=W)
var2 = IntVar()
Checkbutton(master, text="no", variable= var2).grid(row=5, column=2, sticky=W)
Label(master, text="Do you smoke?").grid(row=6)
var3 = IntVar()
Checkbutton(master, text="yes", variable = var3).grid(row=6, column=1, sticky=W)
var4 = IntVar()
Checkbutton(master, text="no", variable= var4).grid(row=6, column=2, sticky=W)
Label(master, text="At about what hour do you usually go to sleep?").grid(row=7)
var5 = IntVar()
Checkbutton(master, text="9-10", variable = var5).grid(row=7, column=1,sticky=W)
var6 = IntVar()
Checkbutton(master, text="11-12", variable= var6).grid(row=7, column=2, sticky=W)
var7 = IntVar()
Checkbutton(master, text="past midnight", variable = var7).grid(row=7, column=3, sticky=W)
Label(master, text="At about what hour do you most often wake up?").grid(row=8)
var8 = IntVar()
Checkbutton(master, text="before the crack of dawn", variable = var8).grid(row=8, column=1, sticky=W)
var9 = IntVar()
Checkbutton(master, text="9-10", variable= var9).grid(row=8, column=2, sticky=W)
var10 = IntVar()
Checkbutton(master, text="11-12", variable = var10).grid(row=8, column=3, sticky=W)
var11 = IntVar()
Checkbutton(master, text="past noon", variable= var11).grid(row=8, column=4, sticky=W)
Label(master, text="If you workout, about how many hours a week do you spend doing so?").grid(row=9)
var12 = IntVar()
Checkbutton(master, text="very often", variable = var12).grid(row=9, column=1, sticky=W)
var13 = IntVar()
Checkbutton(master, text="moderate", variable= var13).grid(row=9, column=2, sticky=W)
var14 = IntVar()
Checkbutton(master, text="on occasion", variable = var14).grid(row=9, column=3, sticky=W)
var15 = IntVar()
Checkbutton(master, text="never", variable = var15).grid(row=9, column=4, sticky=W)
Label(master, text="Which best decribes you?").grid(row=10)
var16 = IntVar()
Checkbutton(master, text="Complete mess", variable = var16).grid(row=10, column=1, sticky=W)
var17 = IntVar()
Checkbutton(master, text="Sometimes messy but relatively organized", variable= var17).grid(row=10, column=2, sticky=W)
var18 = IntVar()
Checkbutton(master, text="Pretty Tidy", variable = var18).grid(row=10, column=3, sticky=W)
var19 = IntVar()
Checkbutton(master, text="Neat Freak", variable= var19).grid(row=10, column=4, sticky=W)
Label(master, text="Are you a light sleeper?").grid(row=11)
var20 = IntVar()
Checkbutton(master, text="yes", variable = var20).grid(row=11, column=1, sticky=W)
var21 = IntVar()
Checkbutton(master, text="no", variable= var21).grid(row=11, column=2, sticky=W)
Label(master, text="Do you have and/or want pets?").grid(row=12)
var22 = IntVar()
Checkbutton(master, text="yes", variable = var22).grid(row=12, column=1, sticky=W)
var23 = IntVar()
Checkbutton(master, text="no", variable= var23).grid(row=12, column=2, sticky=W)
Label(master, text="Do you have a significant other? If no, do you plan on having over night guests of any kind?").grid(row=13)
var24 = IntVar()
Checkbutton(master, text="yes", variable = var24).grid(row=13, column=1, sticky=W)
var25 = IntVar()
Checkbutton(master, text="no", variable = var25).grid(row=13, column=2, sticky=W)
Label(master, text="Which do you prefer?").grid(row=14)
var26 = IntVar()
Checkbutton(master, text="Quiet living space", variable = var26).grid(row=14, column=1, sticky=W)
var27 = IntVar()
Checkbutton(master, text="Noisy living space", variable= var27).grid(row=14, column=2, sticky=W)
var28= IntVar()
Checkbutton(master, text="Some combination of the two", variable = var28).grid(row=14, column=3, sticky=W)
Label(master, text="Do you mind if your roommate has frequent over night guests?").grid(row=16)
var29 = IntVar()
Checkbutton(master, text="yes", variable = var29).grid(row=16, column=1, sticky=W)
var30 = IntVar()
Checkbutton(master, text="no", variable= var30).grid(row=16, column=2, sticky=W)
Label(master, text="Do you mind if your roommate has frequent day time guests? If so what is an approproate time you want guest to leave?").grid(row=17)
var31 = IntVar()
Checkbutton(master, text="yes", variable = var31).grid(row=17, column=1, sticky=W)
var32 = IntVar()
Checkbutton(master, text="no", variable= var32).grid(row=17, column=2, sticky=W)
Label(master, text="Are you willing/expecting to share personal items such as clothes, cleaning supplies, etc?").grid(row=18)
var33 = IntVar()
Checkbutton(master, text="yes", variable = var33).grid(row=18, column=1, sticky=W)
var34 = IntVar()
Checkbutton(master, text="no", variable= var34).grid(row=18, column=2, sticky=W)
Label(master, text="Are you willing to split the grocery bill? If Yes, how much do you usually spend on groceries a month?").grid(row=19)
var35 = IntVar()
Checkbutton(master, text="yes", variable = var35).grid(row=19, column=1, sticky=W)
var36 = IntVar()
Checkbutton(master, text="no", variable= var36).grid(row=19, column=2, sticky=W)
Label(master, text="Are you willing to split chores in shared living spaces?").grid(row=20)
var37 = IntVar()
Checkbutton(master, text="yes", variable = var37).grid(row=20, column=1, sticky=W)
var38 = IntVar()
Checkbutton(master, text="no", variable= var38).grid(row=20, column=2, sticky=W)
Label(master, text="Living preference?").grid(row=21)
var39 = IntVar()
Checkbutton(master, text="Near a big city", variable = var39).grid(row=21, column=1, sticky=W)
var40 = IntVar()
Checkbutton(master, text="Suburbs", variable= var40).grid(row=21, column=2, sticky=W)
var41 = IntVar()
Checkbutton(master, text="Rural area", variable = var41).grid(row=21, column=3, sticky=W)
Label(master, text="'How much are you looking to spend on rent, including utilities, per month?'").grid(row=22)
var42 = IntVar()
Checkbutton(master, text="$800+", variable = var42).grid(row=22, column=1, sticky=W)
var43 = IntVar()
Checkbutton(master, text="$600-$800", variable= var43).grid(row=22, column=2, sticky=W)
var44 = IntVar()
Checkbutton(master, text="$400-$600", variable = var44).grid(row=22, column=3, sticky=W)
var45 = IntVar()
Checkbutton(master, text="$200-$400", variable = var45).grid(row=22, column=4, sticky=W)

e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e6 = Entry(master)
e7 = Entry(master)
e8 = Entry(master)
e9 = Entry(master)
e10 = Entry(master)
e11 = Entry(master)
e12 = Entry(master)
e13 = Entry(master)
e14 = Entry(master)
e15 = Entry(master)
e16 = Entry(master)
e17 = Entry(master)
e18 = Entry(master)
e19 = Entry(master)
e20 = Entry(master)
e21 = Entry(master)
e22 = Entry(master)
e23 = Entry(master)

e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
e4.grid(row=3, column=1)
e5.grid(row=4, column=1)
e18.grid(row=17, column =3)
e20.grid(row=19, column= 3)

Button(master, text= "Quit", command=master.quit).grid(row=23, sticky=W, pady=4)
SubmitButton = Button(master, text="Submit", command=callback)
SubmitButton.grid(row=23, column=1, sticky=W, pady=4)

master.mainloop()

